Disable Certificate Verification on preseed/late_command to Inform Fo…
theforeman/community-templates pull request #315
Opened 2016-11-21 20:25 UTC by markchristopherwest

…reman

This fails when using self signed certificates i.e.: the wget switches should be similar to what is in the finish:

--no-proxy --quiet --output-document=/dev/null --no-check-certificate

2016-11-21 20:35 UTC, mmoll commented
The CA used by the Foreman instance is genertaed from Puppet by default and thus never included in the OS CA cert stores. In what setup do you see what problems exactly?

2016-12-11 21:39 UTC, mmoll commented
@markchristopherwest Ping? Do you, by any chance, run a https-only Foreman instance?

2016-12-15 21:21 UTC, ekohl requested changes

2016-12-15 21:21 UTC, ekohl commented on preseed/provision.erb
> +d-i preseed/late_command string wget -Y off --no-proxy --quiet --output-document=/dev/null --no-check-certificate <%= @static ? "'#{foreman_url('finish')}&static=true'" : foreman_url('finish') %> -O
The ```--output-document=/dev/null``` is redundant since ```-O``` is the same argument and specified later in the line.

2016-12-15 21:21 UTC, ekohl commented on preseed/provision.erb
> +#d-i preseed/late_command string wget -Y off <%= @static ? "'#{foreman_url('finish')}&static=true'" : foreman_url('finish') %> -O /target/tmp/finish.sh && in-target chmod +x /tmp/finish.sh && in-targ
I strongly dislike commented code

2017-01-19 21:13 UTC, mmoll commented
no reaction, closing.

2017-01-19 21:13 UTC, closed without merging