Add export_hostgroup_fact  snippet
theforeman/community-templates pull request #327
Opened 2016-12-15 00:03 UTC by amirfefer

Template part of http://projects.theforeman.org/issues/6952

2017-01-11 11:07 UTC, dLobatog requested changes

2017-01-11 11:07 UTC, dLobatog commented on snippets/export_hostgroup_fact.erb
> +export FACTER_foreman_hostgroup=<%= @host.title %>
`@host.hostgroup.title`

2017-01-11 11:09 UTC, dLobatog commented
@amirfefer Shouldn't this be added to all finish templates? I'm not sure how to add this to userdata though...

2017-03-25 13:28 UTC, mmoll commented
@amirfefer what's the status here?

2017-07-09 00:28 UTC, mmoll commented
@amirfefer ping?

2020-03-04 09:25 UTC, tbrisker commented
Thanks @amirfefer !

2020-03-04 09:25 UTC, closed without merging