Fixes #18509 - configure hostname in finish template
theforeman/community-templates pull request #361
Opened 2017-02-17 13:29 UTC by ares

2017-02-17 22:24 UTC, mmoll commented
can this somehow get merged/unified into the fix_hosts snippet?

2017-03-08 09:03 UTC, ekohl reviewed
I haven't seen a case where this is needed. Is this a situation where the user hasn't set up DNS?

2017-03-08 09:03 UTC, ekohl commented on provisioning_templates/snippet/set_hostname.erb
> +hostname <%= @hostname %>
Should it check if ```hostnamectl``` should be used?

2017-03-08 09:17 UTC, ares commented
> can this somehow get merged/unified into the fix_hosts snippet?

Good point @mmoll, do you think the @host.shortname is preferable over @host.name? That's the only difference. If we agree on one, I can make fix_hosts using set_hostname internally and call the same from kickstart_default_finish.erb

2017-03-08 09:24 UTC, ares commented on provisioning_templates/snippet/set_hostname.erb
> +hostname <%= @hostname %>
Would it be better to use os major/family foreman facts or rather something like `which hostnamectl`?

2017-03-08 09:31 UTC, ekohl commented on provisioning_templates/snippet/set_hostname.erb
> +hostname <%= @hostname %>
I think I'd prefer ```which hostnamectl```

2017-03-10 16:34 UTC, mmoll commented
@ares I have no idea why, but on my rails console, I'm getting the FQDN for both variables.

2017-03-13 09:04 UTC, ares commented
> @ares I have no idea why, but on my rails console, I'm getting the FQDN for both variables.

does the host have a domain associated?

2017-03-13 09:06 UTC, ares commented
> I haven't seen a case where this is needed. Is this a situation where the user hasn't set up DNS?

When I have an image with the hostname hardcoded in it and use it for SSH based provisioning, I need modify it to what I set in foreman as a hostname. How do you set hostname in your env? I think host should know its own name without DNS.

2017-03-13 15:08 UTC, mmoll commented
> does the host have a domain associated?

Yes, it does... however, in general I think FQDN is always good and (if possible) the shortname can be added as second entry

2017-03-17 14:59 UTC, ekohl commented
> When I have an image with the hostname hardcoded in it and use it for SSH based provisioning, I need modify it to what I set in foreman as a hostname.

I didn't consider images and only used kickstarts. In that case Anaconda takes care of it. Thanks for pointing that out :)

2017-03-23 10:01 UTC, ares commented
I've updated the `set_hostname` snippet so it uses `hostnamectl` if it's available (it also sets /etc/hostname). I updated the fix_hosts snippet so it uses set_hostname snippet internally and instead of shortname it uses @host.name now. I could also remove it's direct using and replace it with `set_hostname` but I didn't want to change too much. Let me know if you want me to update 

* provisioning_templates/finish/alterator_default_finish.erb 
* provisioning_templates/user_data/kickstart_default_user_data.erb
* provisioning_templates/user_data/preseed_default_user_data.erb

so it uses set_hostname with variable directly. I think we should keep the snippet here for some time, people might rely on it in their custom templates...

@mmoll and @ekohl, I'd appreciate if guys could take a another look.

2017-03-23 22:18 UTC, mmoll commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.0.1   <%= @hostname -%>\n/' /etc/hosts
I think generating a new /etc/hosts would be better, especially on clud images you never know what's there. Also, isn't that "localhost" entry also needed?

2017-07-25 11:55 UTC, GregSutcliffe commented
This still looks relevant - I do something similar in my image templates :) @ares, are you planning to finish this?

2017-07-31 12:07 UTC, ares commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.0.1   <%= @hostname -%>\n/' /etc/hosts
@mmoll what if I prepared my image with custom hosts file with some specific records? sed should be safe enough... I'm not sure about the localhost, but I suppose it does not hurt to change it to
`sed -i '1s/^/127.0.0.1   <%= @hostname -%> localhost\n/' /etc/hosts`

would that be acceptable?

2017-07-31 12:08 UTC, ares commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.0.1   <%= @hostname -%>\n/' /etc/hosts
also generating new hosts file means, I wouldn't be able to use the snippet twice within the template

2017-07-31 17:56 UTC, mmoll commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.0.1   <%= @hostname -%>\n/' /etc/hosts
I don't know... at least Debian/Ubuntu sets `127.0.1.1 fqdn hostname` per default. I'd rather go for 127.0.0.1 for localhost and the primary IP for the fqdn and hostname...

2017-08-14 17:43 UTC, ares commented
@GregSutcliffe I updated the hosts file according to what @mmoll suggested, could you please take a look?

2017-08-15 09:20 UTC, GregSutcliffe commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.1.1   <%= @hostname -%> <%= @shortname -%>\n/' /etc/hosts
This is different to the old, it doesn't have the `localhost.*` entries on the line

2017-08-15 09:20 UTC, GregSutcliffe commented
One comment, but looks sensible. @mmoll does this look OK now?

2017-08-16 06:02 UTC, ares commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.1.1   <%= @hostname -%> <%= @shortname -%>\n/' /etc/hosts
Since we now rely on this being present from OS and with address 127.0.0.1. We nowadd separate record for 127.0.1.1.

2017-08-16 06:04 UTC, ares commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.1.1   <%= @hostname -%> <%= @shortname -%>\n/' /etc/hosts
Maybe I could move it to second line (sed 2s/) but I don't think it would make a bit difference.

2017-08-16 11:05 UTC, GregSutcliffe commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.1.1   <%= @hostname -%> <%= @shortname -%>\n/' /etc/hosts
Relying on the OS being correct is what got us into this situation in the first place. If we trusted the contents of `/etc/hosts` we wouldn't need to mess with this at all. Given that we're altering a snippet that may be in use (and in the user_data templates, where hosts could have all sorts of wonky base images), shouldn't we try to preserve behaviour?

2017-08-17 09:34 UTC, ares commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.1.1   <%= @hostname -%> <%= @shortname -%>\n/' /etc/hosts
I don't think that's the original motivation (at least in my case). The image already contains /etc/hosts, I choose the FQDN when I do the provisioning, the OS can't know what I had in mind during provisioning. Therefore we to set the hostname as part of provisioning.

The question is what was the motivation for "fixing" the hosts file in fix_hosts.erb snippet. If someone knows or consider that localhost and ipv6 addresses always right, I'm happy to incorporate it here. The question is whether this should be part of "set_hostname" though, maybe it should remain in fix_hosts snippets then.

2017-08-17 13:02 UTC, GregSutcliffe commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.1.1   <%= @hostname -%> <%= @shortname -%>\n/' /etc/hosts
Sure, I get that it's not the motivation for this PR, but you are removing functionality that was present before. I see your point about it not belonging in set_hostname though... but this patch does move from replacing the whole file to changing a single line. That may have consequences for some people who's basic /etc/hosts is incorrect.

I think it's probably an edge case, so I'd go for a merge & a note in the release notes?

2017-08-22 14:43 UTC, ares commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.1.1   <%= @hostname -%> <%= @shortname -%>\n/' /etc/hosts
makes sense, so let's see if others have some insights... I agree to what you suggested

2017-08-22 15:29 UTC, iNecas commented on provisioning_templates/snippet/set_hostname.erb
> +  sed -i '1s/^/127.0.1.1   <%= @hostname -%> <%= @shortname -%>\n/' /etc/hosts
👍

2017-08-24 16:35 UTC, mmoll commented
I didn't test that, but it's looking OK visually. 👍

2017-08-30 12:58 UTC, ekohl requested changes

2017-08-30 12:58 UTC, ekohl commented on provisioning_templates/snippet/set_hostname.erb
> +  echo "<%= @hostname -%>" > /etc/hostname
This is correct for Debian and systemd-based systems. Do you want to do something for EL6 and older?

2017-08-30 12:58 UTC, ekohl commented on provisioning_templates/snippet/set_hostname.erb
> +if grep '^127.0.1.1\s*<%= @hostname -%>\s*<%= @shortname -%>$' /etc/hosts; then
The style is a bit inconsistent. Above it's ```[ `command` ]``` and here just ```grep```. I don't mind which style is used, but I like consistency :) Also ```grep -q```?

2018-04-07 22:06 UTC, mmoll commented
@ares please rebase and have a look into @ekohl's comments, this still can get into 1.18 :)

2018-07-13 11:32 UTC, ares commented
rebased and updated, I hope it's ok for everybody now, @ekohl mind to revisit your review?

2018-07-13 12:24 UTC, ekohl commented on provisioning_templates/snippet/set_hostname.erb
> +if [ -d "/etc/sysconfig" ]; then
I'd test if `/etc/sysconfig/network` exists. I've seen `/etc/sysconfig` exist on some Debian systems because a package placed some files in that directory.

2019-10-11 11:13 UTC, mmoll commented
@ares what's the status here?

2020-01-15 14:31 UTC, lzap commented
Are you planning getting back to this? Good patch, I think `/etc/hosts` changes should be optional tho because that's really only needed when you don't have proper DNS setup. Foreman can provide DNS management and no changes in this file would be necessary usually.

2020-02-18 08:18 UTC, ares commented
Everytime I fix something I get a new request, I'm not sure if I can spend more time on this. I can rebase and update the path at some point I guess.

@lzap how would you like to make this optional? if you read one of the first comments, you'll find the motivation - https://github.com/theforeman/community-templates/pull/361#issuecomment-286050480 Note that this is changing the finish template.

2020-02-28 12:38 UTC, lzap commented
It is assumed that hosts managed by Foreman have proper DNS, therefore no changes of `/etc/hosts` is necessary. Some users tend to manage hosts file entries instead of DNS, then configuration management should be used. However, feel free to send a patch to Foreman templates to do this during provisioning, but only as opt-in via parameter. By default, we do not want to change what OS installers set.

File `/etc/resolv.conf` is managed by NetworkManager from CentOS 6, there is no need of changing it directly. Nameservers must be set in ifcfg setting (DNS1, DNS2) or interactively via NetworkManager CLI, TUI or applet.

2020-02-28 12:38 UTC, closed without merging

2020-02-28 17:09 UTC, ares commented
Ok, I'll repeat the last time, this is not about properly working DNS in the infrastructure. If you do image based provisioning, you have no idea what the image has in /etc/hosts. That has higher priority than DNS. This would fix it. Setting FQDN in hosts is probably always a good idea. There was overall support for this, not sure what changed.

2020-03-02 11:59 UTC, lzap commented
Well, official Fedora/RH images have no `/etc/hosts` entries (localhost only), I suppose: https://github.com/weldr/lorax/blob/master/docs/fedora-openstack.ks

If you create your own image with garbage, it's not our job to fix this. We even ship a tool with RHEL and Fedora that is supposed to clean such images from the garbage!

http://libguestfs.org/virt-sysprep.1.html

2020-03-02 12:04 UTC, lzap commented
I am fine with merging *opt-in* deployment of `/etc/hosts`. I'd prefer it to be a separate template and it could be rendered via `curl http://foreman/unattended/script > /etc/hosts`.