Add support for static networking in the autoyast templates.
theforeman/community-templates pull request #377
Opened 2017-03-24 07:41 UTC by hboetes

I noticed the Suse based installs didn't support static networking, unlike debian and redhat based systems, and I needed it for my project.

2017-03-24 13:29 UTC, Klaas- commented on provisioning_templates/provision/autoyast_default.erb
> +        <nameserver><%= @host.subnet.dns_secondary %></nameserver>
I think we should check for presence of those nameservers, at least the secondary one - check the other templates: something like this:
<% if @host.subnet.dns_secondary.present? -%>
        <nameserver><%= @host.subnet.dns_secondary %></nameserver>
<% end -%>

2017-03-24 13:38 UTC, Klaas- commented on provisioning_templates/provision/autoyast_default.erb
> +          <broadcast></broadcast>
I don't think you'll need this line

2017-03-24 15:21 UTC, mmoll commented on provisioning_templates/provision/autoyast_default.erb
> +        <ethtool_options>autoneg on</ethtool_options>
is this line really needed?

2017-03-24 15:22 UTC, mmoll commented on provisioning_templates/provision/autoyast_default.erb
> +        <device>eth0</device>
I guess (but we do have the same problem for DHCP also, anyway...) that's not always correct with persistent device naming in newer versions?

2017-03-24 15:22 UTC, mmoll commented on provisioning_templates/provision/autoyast_default.erb
> +        <netmask>-</netmask>
what does the dash mean?

2017-03-24 17:02 UTC, ekohl requested changes

2017-03-24 17:02 UTC, ekohl commented on provisioning_templates/provision/autoyast_default.erb
> +          <bootproto>static</bootproto>
The XML indenting will look weird here.

2017-03-24 17:02 UTC, ekohl commented on provisioning_templates/provision/autoyast_default.erb
> +        <% if @host.subnet.respond_to?(:dhcp_boot_mode?) -%>
If it responds to boot mode but boot mode is set to DHCP then you will still end up with static networking.

2017-03-27 06:18 UTC, hboetes commented on provisioning_templates/provision/autoyast_default.erb
> +        <% if @host.subnet.respond_to?(:dhcp_boot_mode?) -%>
I c&p this line from the kickstart template, what do you propose I should use?

2017-03-27 06:19 UTC, hboetes commented on provisioning_templates/provision/autoyast_default.erb
> +        <netmask>-</netmask>
I don't know, but I find it all over the docs. https://www.suse.com/documentation/sles-12/book_autoyast/data/createprofile_network.html

2017-03-27 06:22 UTC, hboetes commented on provisioning_templates/provision/autoyast_default.erb
> +        <ethtool_options>autoneg on</ethtool_options>
That depends on the default configuration in autoyast. autoneg is what most people will want to have.

2017-03-27 08:48 UTC, mmoll commented on provisioning_templates/provision/autoyast_default.erb
> +        <ethtool_options>autoneg on</ethtool_options>
Isn't autoneg the default? So this line can get ommited?

2017-03-27 08:50 UTC, mmoll commented on provisioning_templates/provision/autoyast_default.erb
> +        <netmask>-</netmask>
ah, I see 👍

2017-03-27 08:52 UTC, hboetes commented on provisioning_templates/provision/autoyast_default.erb
> +        <device>eth0</device>
Fixed in my latest commit which supports multiple interfaces

2017-03-27 08:53 UTC, hboetes commented on provisioning_templates/provision/autoyast_default.erb
> +          <bootproto>static</bootproto>
I noticed as well. What can I do about it?

2017-03-27 09:00 UTC, mmoll commented
Regarding `dhcp_boot_mode`, the `respond_to?` is only for identifying if the Foreman in question does support the distinction. As the templates are now versioned, this can/should be ommited.

Regarding the distinction between DHCP and static mode, here is the simple code used in the preseed networking snippet:
```
<% @host.managed_interfaces.each do |interface| -%>
  <% next if !interface.managed? || interface.subnet.nil? || interface.primary -%>
  <% subnet = interface.subnet -%>
  <% dhcp = subnet.nil? ? false : subnet.dhcp_boot_mode? -%>
  <% if dhcp -%>
    [do dhcp things here]
  <% else -%>
    [do static things here]
  <% end -%>
<% end -%>
```

2017-03-27 09:06 UTC, mmoll commented on provisioning_templates/provision/autoyast_default.erb
> +          <bootproto>static</bootproto>
indenting it correctly? ;)

2017-03-27 09:59 UTC, hboetes commented on provisioning_templates/provision/autoyast_default.erb
> +        <ethtool_options>autoneg on</ethtool_options>
ok, consider it gone.

2017-03-27 11:16 UTC, mmoll commented
Again, `<% if @host.subnet.respond_to?(:dhcp_boot_mode?) -%>` does _not_ check if that subnet is in DHCP or static mode.

You copypasted some code from the kickstart snippet, but in your the current code there's no usage of the variables `virtual`, `vlan`, `alias-type` and even `dhcp` of the respective subnet. Please double-check your code and also make sure, DHCP installs work as intended.

2017-03-27 11:17 UTC, mmoll requested changes
this needs to get into a working state first

2017-03-27 14:14 UTC, hboetes commented
If you guys want me to join all these commits, I'll gladly oblige.

2017-03-30 21:17 UTC, mmoll commented
@hboetes thanks for following up on this, looking much better now.

I squashed all your commit together into one and then added one commit with some refactorings.

This is still untested and I don't know when I will have time to test this with real machines, in the meanwhile I'd ask @ares to have a look. 👀

2017-04-11 14:14 UTC, Klaas- commented
I think there is another issue here we should address: the device identifiers are not enforced by foreman at the moment, if they aren't set the network interfaces won't be configured  properly (at least if I didn't mess up my test case :) ). I'm not sure how one would work around that - could we just set a device name based on a loop-counter or can we do it like the rhel networking snippet does - set no device identifiers and use the mac to identify the device?

2017-04-11 15:27 UTC, mmoll commented
I did think about that, but at the end this is already an improvement over the current situation, where eth0 is also hardcoded. I hope to test this in the next days and merge it, further improvements shoudl go into further PRs.

2017-04-14 22:53 UTC, merged

2017-04-14 23:05 UTC, mmoll commented
merged, thanks @hboetes!