Fix bond deployments
theforeman/community-templates pull request #402
Opened 2017-06-20 08:54 UTC by xprazak2

Needs a change in [Foreman](https://github.com/theforeman/foreman/pull/4583) to work.

2018-01-08 16:18 UTC, ares requested changes
nearly there :-)

2018-01-08 16:18 UTC, ares commented on provisioning_templates/snippet/kickstart_networking_setup.erb
> +<%-   interface_identifier = @host.bond_interfaces.map(&:identifier).include?(interface.attached_to) ? interface.identifier : nil %>
the map must be rewritten to `.map { |i| i.identifier }` syntax, the shorter was removed from safe_mode

2018-01-08 16:18 UTC, ares commented on provisioning_templates/snippet/kickstart_ifcfg_generic_interface.erb
> +<%- if @interface.virtual? && ((!@subnet.nil? && @subnet.has_vlanid?) || (@interface.tag.present? && @interface.vlanid.present?)) -%>
why the tag must be present? the vlanid is taking tag into consideration, phrasing the code

```
    def vlanid
      # Determine a vlanid according to the following cascading rules:
      # 1. if the interface has a tag, use that as the vlanid
      # 2. if the interface has a v4 subnet with a non-blank vlanid, use that
      # 3. if the interface has a v6 subnet with a non-blank vlanid, use that
      # 4. if no reasonable vlanid was determined, then return an empty string
      #
      # In case the v4 and v6 subnet are both present, they should have the same
      # vlanid. If they have a different vlanid, this is probably an error in the
      # user's database. There is no way of determining the real vlanid, so we
      # pick the v4 one unless it turns out to be blank.

      return self.tag unless self.tag.blank?
      return self.subnet.vlanid if self.subnet && self.subnet.vlanid.present?
      return self.subnet6.vlanid if self.subnet6 && self.subnet6.vlanid.present?
      return ''
    end
```

2018-01-08 16:18 UTC, ares commented on provisioning_templates/snippet/kickstart_ifcfg_generic_interface.erb
> +<%- if @interface.virtual? && ((!@subnet.nil? && @subnet.has_vlanid?) || (@interface.tag.present? && @interface.vlanid.present?)) -%>
actually testing the deployment without this part of change seems to work well

2018-01-10 10:00 UTC, xprazak2 commented
I updated as suggested.

2018-01-11 11:52 UTC, ares approved these changes

2018-01-11 11:53 UTC, ares commented
The linked PR just got in so this one is also good to go, I'll create sync PR since it would not work in nightly without this change while the redmine issue would indicate it's resovled...

Thanks @xprazak2!

2018-01-11 11:53 UTC, merged