Add more puppet job templates
theforeman/community-templates pull request #489
Opened 2018-06-28 07:42 UTC by dgoetz

This pull request adds more puppet job templates.

* Disabling of the agent including a comment which should help the local admin to see why it was disabled. I also created a feature request to have a macro for the user executing the job to add it to the comment. (https://projects.theforeman.org/issues/23955)
* Enabling of the agent
* Installation of puppet modules to provide something similar to the ansible roles. For the Boolean options I created another feature request, for now I think forcing the user to type true is fine. (https://projects.theforeman.org/issues/23956)

I am not sure if the naming of the files is fine but I tried to align it to the other templates.

2018-11-12 16:03 UTC, dgoetz commented
Added the current_user macro available from 1.20 to the disable job.

2018-11-19 13:02 UTC, ekohl approved these changes
It looks correct, but I'm not that familiar with job templates.

2018-11-20 19:14 UTC, ares requested changes
Looks all great, there are extra empty lines, which would be nice to be removed. I haven't tested yet, but from reading it looks great!

2018-11-20 19:14 UTC, ares commented on job_templates/puppet_agent_disable_-_ssh_default.erb
> +%>
Ideally add - before % to avoid extra line, I suppose you exported this from Foreman, so we may need to update oir exporter

2018-11-21 07:56 UTC, dgoetz commented
Add the `-` to `%>` and removed the empty lines. 
I am not sure if I wrote them manually and then imported them the first time or did it the other way.

2019-01-10 11:32 UTC, ares approved these changes

2019-01-10 11:32 UTC, ares commented
Thanks @dgoetz and sorry for the delay. This works great, merging!

2019-01-10 11:32 UTC, merged