Fixes #25166 - Add Applicable errata report
theforeman/community-templates pull request #524
Opened 2018-10-10 11:36 UTC by mbacovsky

2018-10-10 11:41 UTC, mbacovsky commented
PR in Katello https://github.com/Katello/katello/pull/7747 is required for this report.
I'd like to ask reviewer to check if the queries could be further optimised and if the data collected match what was requested.

2018-10-10 15:10 UTC, ares requested changes
few smaller things, meanwhile I'm building an environment where I'll be able to test

2018-10-10 15:10 UTC, ares commented on report_templates/applicable_errata.erb
> +%>
missing `-`

2018-10-10 15:10 UTC, ares commented on report_templates/applicable_errata.erb
> +- name: Output format
as suggested elsewhere, format should not be in input I think

2018-10-10 15:10 UTC, ares commented on report_templates/applicable_errata.erb
> +<%- load_hosts(search: input('Hosts filter'), includes: [:operatingsystem,:applicable_errata,:lifecycle_environment]).each_record do |host| -%>
please add spaces after commas in array

2018-10-10 22:34 UTC, mbacovsky commented
@ares, updated

2018-10-11 05:36 UTC, ares approved these changes

2018-10-11 05:36 UTC, ares commented
pending Katello PR merge

2018-10-12 11:12 UTC, ares commented
Thanks @mbacovsky, merging!

2018-10-12 11:13 UTC, merged