Fixes #25165 - Add Registered hosts report
theforeman/community-templates pull request #525
Opened 2018-10-10 11:55 UTC by mbacovsky

PR Katello/katello#7747 is required for this report.
I'd like to ask reviewer to check if the queries could be further optimized and if the data collected match what was requested.

2018-10-10 14:45 UTC, ares requested changes
the similar feedback as elsewhere, otherwise seems to work fine

2018-10-10 14:45 UTC, ares commented on report_templates/registered_hosts.erb
> +%>
missing `-`

2018-10-10 14:45 UTC, ares commented on report_templates/registered_hosts.erb
> +- name: Output format
as in other PR, I don't think this should be exposed as input as of now

2018-10-10 22:30 UTC, mbacovsky commented
@ares, updated.

2018-10-11 05:35 UTC, ares commented on report_templates/registered_hosts.erb
> +<%- load_hosts(search: input('Hosts filter'), includes: [:operatingsystem,:subscriptions,:fact_values,:fact_names,:applicable_errata,:applicable_rpms]).each_record do |host| -%>
sorry, I missed that in first review, could you please add spaces after commas here?

2018-10-12 11:58 UTC, mbacovsky commented
@ares fixed, please squash it during the merge

2018-10-12 12:03 UTC, ares approved these changes

2018-10-12 12:03 UTC, ares commented
Thanks @mbacovsky, merging

2018-10-12 12:03 UTC, merged