Fixes #25163 - Add Subscriptions report
theforeman/community-templates pull request #526
Opened 2018-10-10 12:14 UTC by mbacovsky

PR Katello/katello#7747 is required for this report.
I'd like to ask reviewer to check if the queries could be further optimized and if the data collected match what was requested.

2018-10-10 14:41 UTC, ares requested changes
one nit and one thing to consider, otherwise works well (tested with patched katello)

2018-10-10 14:41 UTC, ares commented on report_templates/subscriptions.erb
> +%>
use - in here, otherwise I'm getting empty line as first thing in the report

2018-10-10 14:41 UTC, ares commented on report_templates/subscriptions.erb
> +- name: Output format
Is yaml formatter stable enough already? I'm not sure I'd expose this as an input, once we think it's ready, we should have that as separate parameter for generating the report (as long as all reports will always support it). Overridding it per template using user input seems like something we'd need to remove in future.

2018-10-10 22:22 UTC, mbacovsky commented on report_templates/subscriptions.erb
> +- name: Output format
I consider yaml formatter stable enough as it is basically `to_yaml` called on a list of hashes with filtered content. I don't expect any troubles there. We didn't do a performance testing, but that was not done neither for the csv render. I'll remove the input for the format till we agree we want it there.

2018-10-10 22:28 UTC, mbacovsky commented
@ares, thanks for the review, updated.

2018-10-12 08:28 UTC, ares approved these changes

2018-10-12 11:12 UTC, ares commented
Thanks @mbacovsky, merging!

2018-10-12 11:12 UTC, merged