refs #25285 - support multiple repos in Kickstart
theforeman/community-templates pull request #531
Opened 2018-10-23 13:24 UTC by stbenjam

2018-10-23 13:32 UTC, ekohl approved these changes
Looks correct to me.

2018-10-25 07:21 UTC, lzap commented
I have some comments in core, but have you tried snapshot tests in core? I believe they can fail since `@repo` was unused. Just checking.

2018-10-25 07:27 UTC, timogoebel commented
Did you leave out the `--install` parameter for the repo by choice?

2018-10-25 14:09 UTC, stbenjam commented
Mostly just thinking about Katello, where we would provide the content through subscription-manager.  I can make it conditional.

2018-11-01 12:32 UTC, lzap requested changes
Parsing errors.

But during my testing `@additional_media` is `nil`. Need to dig it up.

2018-11-01 12:32 UTC, lzap commented on provisioning_templates/provision/kickstart_default.erb
> +% @additional_media.each do |medium| -%>
```suggestion
<% @additional_media.each do |medium| -%>
```

2018-11-01 12:32 UTC, lzap commented on provisioning_templates/provision/kickstart_default.erb
> +repo --name <%= medium[:name] %> --baseurl <%= medium[:url %> <%= medium[:install] ? ' --install' : '' %>
```suggestion
repo --name <%= medium[:name] %> --baseurl <%= medium[:url] %> <%= medium[:install] ? ' --install' : '' %>
```

2018-11-01 12:54 UTC, lzap commented
One important change required, do not use symbols to access keys of repo. Change here or make sure these are hashes with indifferent access.

2018-11-01 13:25 UTC, stbenjam commented
I think it's better if the Foreman side makes it indifferent access, we can't be entirely sure what a plugin medium provider might do.  

Apologies this PR wasn't in a good state - should be OK now, but going to reverify with new changes to Foreman side and fix the safe mode issue you noticed.

2018-11-01 14:05 UTC, lzap approved these changes
Sure. NP don't apologize, that's why we do reviews. Looks good.

2018-11-02 08:35 UTC, lzap approved these changes
And it works great! Many thanks, excellent improvement.

2018-11-02 08:36 UTC, merged