Add FIPS support
theforeman/community-templates pull request #560
Opened 2019-03-01 09:29 UTC by ares

This takes custom logic from https://github.com/RedHatSatellite/satellite6-fips-client so we have FIPS support available in upstream templates.

@sideangleside, mind to check whether I missed something? Potentially, @pondrejk would you mind testing?

2019-03-01 10:17 UTC, iNecas requested changes
Test failures related

2019-03-01 10:18 UTC, iNecas commented
Should the templates for other bootloaders (PXEGrub, iPXE) udpated as well?

2019-03-01 12:00 UTC, iNecas commented on provisioning_templates/snippet/fips_packages.erb
> +name: fips_packages
missing `model` and `snippet` attributes

2019-03-01 12:43 UTC, ares commented
This should fix tests and add the same to PXEGrub and PXEGrub2. I'm not sure about iPXE, IIUC fips is required only in stage2? @lzap could you advise?

2019-03-01 13:46 UTC, iNecas commented
Created an issue for this for better tracking https://projects.theforeman.org/issues/26203

Tested and works well: the provisioned host had fips enabled after provisioning and the installation worked without issues.

Deferring to @lzap regarding the iPXE question.

Also opened discovery counterpart https://github.com/theforeman/foreman_discovery/pull/473 - reviews welcome there.

2019-03-05 08:41 UTC, lzap commented
Well iPXE works the same way as PXELinux, except it uses http by default in our case. So sure, add the parameter there as well, host params are available in the iPXE context. There is no FIPS mode in iPXE itself.

2019-03-05 09:13 UTC, ares commented
ok, I updated the kickstart_default_ipxe.erb as well, please take another look

2019-03-05 10:47 UTC, iNecas approved these changes
All good now. Thanks @ares

2019-03-05 10:48 UTC, merged

2019-03-05 10:48 UTC, iNecas commented
Tested and works well. Thanks @ares