Fixes #27996 - Add template for entitlements report
theforeman/community-templates pull request #631
Opened 2019-10-03 11:41 UTC by xprazak2

Needs:
https://github.com/theforeman/foreman/pull/7081
https://github.com/Katello/katello/pull/8369

2019-10-04 13:33 UTC, ares requested changes
there are few "rubocoppy" nits, but looks really great! of course can only be merged after dependencies are in, but looking forward to merge this one :-)

2019-10-04 13:33 UTC, ares commented on report_templates/entitlements.erb
> +  <%- host.pools.each do |pool| -%>
usually we do the indentation inside of erb tag, see https://github.com/theforeman/community-templates/blob/develop/report_templates/applicable_errata.erb#L24-L26 for example

2019-10-04 13:33 UTC, ares commented on report_templates/entitlements.erb
> +          'Cores':  host.cores,
two spaces after colon

2019-10-04 13:33 UTC, ares commented on report_templates/entitlements.erb
> +
I think this would cause extra empty line e.g. in csv output

2019-10-04 13:33 UTC, ares commented on report_templates/entitlements.erb
> +
I think this would cause extra empty line, ideally also add - to the comment closing erb tag

2019-10-07 05:41 UTC, xprazak2 commented
Updated with style fixes.

2019-10-08 08:41 UTC, ares reviewed
looks great, waiting on depending PRs before testing this

2019-10-16 14:06 UTC, ares approved these changes
Tested with Katello PR (foreman is in already) and it's working just fine, ready to be merged after Katello PR gets in.

2019-10-17 12:48 UTC, ares commented
Thanks @xprazak2, merging!

2019-10-17 12:48 UTC, merged