fixes# 28168 - added registered users template
theforeman/community-templates pull request #660
Opened 2019-11-18 12:18 UTC by domitea

2019-11-20 08:10 UTC, ares requested changes
Looks good to me, needs https://github.com/theforeman/foreman/pull/7155 to be in first in order to test. I left just one nit pick.

2019-11-20 08:10 UTC, ares commented on report_templates/registered_users.erb
> +name: List of registered users
I'd call it just `Registered users` to remain consistent with other reports. Reports are lists usually, so we don't need to repeat that information

2019-11-20 12:40 UTC, ares commented on report_templates/registered_users.erb
> +  <%-  report_row({
the indentation here is incorrect, it should start on col 0 and the indentation should be done inside of the ERB, see other reports for an example

2019-11-25 08:20 UTC, ares commented on report_templates/registered_users.erb
> +         'Login': user.login,
sorry for nitpicking, but the indentation should be by 2 spaces, this is 3 spaces comparing to the line above

2019-11-28 08:44 UTC, domitea commented
Is it right now? @ares

2019-12-03 15:57 UTC, ares approved these changes
Good, tested this with the linked PR and works great! Ready to merge when core PR gets in

2019-12-08 00:41 UTC, merged

2019-12-08 00:41 UTC, mmoll commented
merged, díky @domitea!