Fixes #664
theforeman/community-templates pull request #665
Opened 2019-11-26 16:08 UTC by jpasqualetto

Replace @host.mac variable by the variable mac, defined on the beginning of the template and which is properly defined as the mac address of the provision interface.

2019-11-26 16:22 UTC, ekohl requested changes
The change itself looks good, but could you improve the commit message? Using `#xxx` refers to Redmine issues and not Github issues. We also prefer for it to describe the issue rather than an issue number. https://github.com/theforeman/community-templates/commit/34f4357d566f313eccdf8af1b46ef5598bb7e265 is an example of how we typically write commit messages though it doesn't have to refer to a (Redmine) issue like https://github.com/theforeman/community-templates/commit/7390618d0a80567c56e0a4cbf815f5edb18d858c demonstrates.

2019-11-26 18:08 UTC, jpasqualetto commented
I changed the commit message as requested and also the PR title. Hope it's ok now.

2019-11-26 18:21 UTC, ekohl commented
Slightly nit picking, but the convention is to treat the first line as a summary and ideally limit it to ~max 72 chars. If there's more, add a newline and a body. https://chris.beams.io/posts/git-commit/ has a proper background. Doing this makes it easier to review, merge and and decide whether it needs a cherry pick into a stable release. The reviewer (in this case me) will be thankful :)

2019-11-26 18:32 UTC, jpasqualetto commented
Ok, giving it another try and taking notes for next time.

2019-11-26 19:01 UTC, ekohl approved these changes

2019-11-26 19:02 UTC, merged

2019-11-26 19:02 UTC, ekohl commented
Thanks!

@tbrisker looks like this is a bug that we should cherry pick.

2019-11-27 08:41 UTC, tbrisker commented
Thanks, cherry-picked into 1.24 as 92f1329